### ISSUE TITLE
problem with icons in rss tab

### ISSUE THREAD

**Issue by b-user** [BaraShiro/Material-qBittorrent#1]
The icons in rss don't go well with the material design (qbittorrent 4.6.4+)
![464](https://github.com/user-attachments/assets/118e4cef-3df1-435e-949d-029739d13e4b)

**Comment by BaraShiro** [comment]
Nice catch. I fixed it in the latest release. 
![image](https://github.com/user-attachments/assets/ff0ec413-f2f1-4552-85bd-263e63b9000f)
