### ISSUE TITLE
The theme is not present in the list of themes 

### ISSUE THREAD

**Issue by b-user** [BaraShiro/Material-qBittorrent#2]
The theme is not present in the list of themes:
https://github.com/qbittorrent/qBittorrent/wiki/List-of-known-qBittorrent-themes

@thalieht, please add

**Comment by thalieht** [comment]
Sorry, now all edits to the wiki are required to go through a PR in https://github.com/qbittorrent/wiki so there's no difference if i make the PR or anyone else.
