### ISSUE TITLE
Progress Bar is too thin and the percentage should be inside the progress bar

### ISSUE THREAD

**Issue by Pentaphon** [BaraShiro/Material-qBittorrent#4]
I realize you are trying to make the client look different but I think the current progress bar is a mistake. The bar is too thin and the percentage on the left hand side is a waste of space. You should make a thick green bar with the percentage inside it. 

![{9063806C-8123-438D-86A5-81648922CF52}](https://github.com/user-attachments/assets/58bf3813-6a49-45c3-88a0-f5dcaa727dfc)

**Comment by BaraShiro** [comment]
I'm really just trying to follow Material Design, see https://m3.material.io/components/progress-indicators/overview

**Comment by Pentaphon** [comment]
> I'm really just trying to follow Material Design, see https://m3.material.io/components/progress-indicators/overview

Fair enough. You can close this if you feel strongly about keeping to material design.
