### ISSUE TITLE
Downloading text and icon should be blue and the Uploading text and icon should be green

### ISSUE THREAD

**Issue by Pentaphon** [BaraShiro/Material-qBittorrent#5]
Right now, the downloading text and icon is green like so:
![{8B4130EE-D4F3-4E32-AF98-3887EF329A54}](https://github.com/user-attachments/assets/b68ec128-6ee9-43a9-96cb-93b1b502c16d)

I think the downloading text should be blue, like a torrent of water flowing to you. Or a water tap filling up a bucket, as data fills up to 100%

![water](https://github.com/user-attachments/assets/c604dbad-8dcd-45af-8674-fdc8d69fa915)

Likewise, the uploading text should be green, the color of a sprouting seedling, which matches the theme of seeding, the green leaves going out to others in the swarm. 

![seeding](https://github.com/user-attachments/assets/54b90ca3-63ff-455f-83fd-a778d4214f16)

Likewise, the icons should also be switched. 

![{5E0B75A2-D117-480C-B50B-55236E2E28BD}](https://github.com/user-attachments/assets/5e068adf-3b6c-4bb5-a26a-3c64cbc49a13)

Please consider switching the colors.

**Comment by BaraShiro** [comment]
Green for download and blue for upload is the qBittorrent default. I have no intention of changing this.

**Comment by Pentaphon** [comment]
> Green for download and blue for upload is the qBittorrent default. I have no intention of changing this.

The designer of the current qBittorrent theme agreed with me on my issue asking for this to be changed at my issue here: https://github.com/qbittorrent/qBittorrent/issues/21448

If he decides to go along with my proposed changes, I'll let you know.
